
package com.ct10000.beian;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Jul 14 11:21:24 CST 2017
 * Generated source version: 2.0.4-incubator
 * 
 */
 
public class QueryBeianStatusPortType_QueryBeianStatusHttpPort_Server{

    protected QueryBeianStatusPortType_QueryBeianStatusHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new QueryBeianStatusPortTypeImpl();
        String address = "http://127.0.0.1:8080/SbsInterface/ws/queryBeianStatus";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new QueryBeianStatusPortType_QueryBeianStatusHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exitting");
        System.exit(0);
    }
}
