
package com.ct10000.beian;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Jul 14 11:21:24 CST 2017
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://beian.ct10000.com/queryBeianStatus", name = "queryBeianStatusPortType")

public interface QueryBeianStatusPortType {

    @WebMethod(operationName = "jrd_querybeianstatus")
    @RequestWrapper(localName = "jrd_querybeianstatus", targetNamespace = "http://beian.ct10000.com/queryBeianStatus", className = "com.ct10000.beian.JrdQuerybeianstatus")
    @ResponseWrapper(localName = "jrd_querybeianstatusResponse", targetNamespace = "http://beian.ct10000.com/queryBeianStatus", className = "com.ct10000.beian.JrdQuerybeianstatusResponse")
    @WebResult(name = "out", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
    public java.lang.String jrdQuerybeianstatus(
        @WebParam(name = "jrdId", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        java.lang.Long jrdId,
        @WebParam(name = "userName", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        java.lang.String userName,
        @WebParam(name = "randVal", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        java.lang.String randVal,
        @WebParam(name = "time", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        long time,
        @WebParam(name = "hashAlgorithm", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        int hashAlgorithm,
        @WebParam(name = "queryConditionType", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        int queryConditionType,
        @WebParam(name = "queryCondition", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        java.lang.String queryCondition,
        @WebParam(name = "sign", targetNamespace = "http://beian.ct10000.com/queryBeianStatus")
        java.lang.String sign
    );
}
