
package com.ct10000.beian;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.ct10000.beian.QueryBeianStatusPortType;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Jul 14 11:21:24 CST 2017
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "queryBeianStatus", targetNamespace = "http://beian.ct10000.com/queryBeianStatus", wsdlLocation = "file:queryBeianStatus.wsdl")
public class QueryBeianStatus extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://beian.ct10000.com/queryBeianStatus", "queryBeianStatus");
    public final static QName QueryBeianStatusHttpPort = new QName("http://beian.ct10000.com/queryBeianStatus", "queryBeianStatusHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:queryBeianStatus.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:queryBeianStatus.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QueryBeianStatus(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryBeianStatus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryBeianStatus() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QueryBeianStatusHttpPort
     */
    @WebEndpoint(name = "queryBeianStatusHttpPort")
    public QueryBeianStatusPortType getQueryBeianStatusHttpPort() {
        return (QueryBeianStatusPortType)super.getPort(QueryBeianStatusHttpPort, QueryBeianStatusPortType.class);
    }

}
